import turtle

tortuga = turtle.Turtle()
#Margen rara
tortuga.speed(10)
tortuga.penup()
tortuga.goto(-420, -220)
tortuga.pendown()
tortuga.pensize(5)
tortuga.forward(840)
tortuga.right(90)
tortuga.forward(40)
tortuga.right(90)
tortuga.forward(40)
tortuga.right(90)
tortuga.forward(620)
tortuga.right(90)
tortuga.forward(40)
tortuga.right(90)
tortuga.forward(40)
tortuga.right(90)
tortuga.forward(840)
tortuga.right(90)
tortuga.forward(40)
tortuga.right(90)
tortuga.forward(40)
tortuga.right(90)
tortuga.forward(620)
tortuga.right(90)
tortuga.forward(40)
tortuga.right(90)
tortuga.forward(40)
tortuga.right(90)

#espiral color
tortuga.penup()
tortuga.goto(-230,180)
tortuga.pendown()
tortuga.speed(16)
for espiral in range(50):
    for c in ('blue', 'red', 'green'):
        tortuga.color(c)
        tortuga.forward(espiral)
        tortuga.right(30)

tortuga.pencolor('blue')
#Letra C
tortuga.speed(3)
tortuga.penup()
tortuga.goto(-280,-45)
tortuga.pendown()
tortuga.pensize(14)
tortuga.setheading(90)
tortuga.forward(12)
tortuga.left(90)
tortuga.circle(80, 180)
tortuga.left(90)
tortuga.forward(12)

#Letra a
tortuga.speed(3)
tortuga.penup()
tortuga.goto(-140, -130)
tortuga.pendown()
tortuga.circle(50)
tortuga.penup()
tortuga.goto(-180, -25)
tortuga.pendown()
tortuga.penup()
tortuga.goto(-130,-180)
tortuga.pendown()
tortuga.forward(90)

#Letra r
tortuga.speed(2)
tortuga.penup()
tortuga.goto(-90,-180)
tortuga.pendown()
tortuga.forward(90)
tortuga.right(90)
tortuga.forward(30)
tortuga.right(90)
tortuga.forward(30)

#letra l 
tortuga.speed(2)
tortuga.penup()
tortuga.goto(-30, -40)
tortuga.pendown()
tortuga.forward(140)

#letra o
tortuga.speed(3)
tortuga.penup()
tortuga.goto(10, -130)
tortuga.pendown()
tortuga.circle(50)

#letra s
tortuga.speed(2)
tortuga.penup()
tortuga.goto(190, -80)
tortuga.pendown()
tortuga.right(90)
tortuga.forward(50)
tortuga.left(90)
tortuga.forward(50)
tortuga.left(90)
tortuga.forward(50)
tortuga.right(90)
tortuga.forward(50)
tortuga.right(90)
tortuga.forward(50)

#Estrella mandala
tortuga.speed(10)
tortuga.penup()
tortuga.goto(200,180)
tortuga.pendown()
tortuga.pencolor('Black')
tortuga.pensize(1)
for _ in range(36):
    for _ in range(5):
        tortuga.forward(100)
        tortuga.right(144)
    tortuga.right(10)

turtle.done()
tortuga.mainloop()